// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCRxjIENtIK56gn_VyWpg1oNmHz-vmF6U',
    appId: '1:530007775390:web:896afc0a098b1c6d35438f',
    messagingSenderId: '530007775390',
    projectId: 'first-project-53113',
    authDomain: 'first-project-53113.firebaseapp.com',
    storageBucket: 'first-project-53113.firebasestorage.app',
    measurementId: 'G-2W8W30Z8DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXW-FrMC73CTCgeOJoh663s_iHuyxyDy8',
    appId: '1:530007775390:android:d67eada4b946763535438f',
    messagingSenderId: '530007775390',
    projectId: 'first-project-53113',
    storageBucket: 'first-project-53113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtf7-ezphTvnDNgMIfXNCOOpfZUECCLp0',
    appId: '1:530007775390:ios:6e182029af4f315535438f',
    messagingSenderId: '530007775390',
    projectId: 'first-project-53113',
    storageBucket: 'first-project-53113.firebasestorage.app',
    iosBundleId: 'com.example.secretary',
  );
}
